enum ConsultType {
  ROUTINE_CHECKUP = 'ROUTINE_CHECKUP',
  URGENT_CARE = 'URGENT_CARE',
  FOLLOW_UP = 'FOLLOW_UP',
  SPECIALIZED = 'SPECIALIZED',
  PRENATAL = 'PRENATAL',
  PEDIATRIC = 'PEDIATRIC',
  PSYCHIATRIC = 'PSYCHIATRIC',
  DENTAL = 'DENTAL',
  GERIATRIC = 'GERIATRIC',
  TELEMEDICINE = 'TELEMEDICINE',
}

export default ConsultType;
